language: android

jdk: oraclejdk8

android:
  components:
  - build-tools-20.0.0

script: ./gradlew clean build -PdisablePreDex

notifications:
  email: false
  on_success: always
  on_failure: always
